var gameover_res={}
var gameover_scn={"image6":{"id":"image6","type":"image","visible":"true","x":0,"y":0,"width":"320","height":"480","image":"bg","scaleX":0.8695652173913043,"scaleY":0.8333333333333334,"rotation":0,"physics":false,"dynamic":true,"body":"default","mass":10,"fixedRotation":true},"sprite7":{"id":"sprite7","type":"sprite","visible":"true","x":115,"y":234,"width":"64","height":"64","image":"restart","frame":0,"scaleX":0.6666666666666666,"scaleY":0.6666666666666666,"rotation":0,"physics":false,"dynamic":true,"body":"default","mass":10,"fixedRotation":true,"events":{"onInputDown":"sprite7_onInputDown"}},"image8":{"id":"image8","type":"image","visible":"true","x":46,"y":142,"width":102,"height":42,"image":"game","scaleX":1,"scaleY":1,"rotation":0,"physics":false,"dynamic":true,"body":"default","mass":10,"fixedRotation":true},"image9":{"id":"image9","type":"image","visible":"true","x":150,"y":170,"width":88,"height":42,"image":"over","scaleX":1,"scaleY":1,"rotation":0,"physics":false,"dynamic":true,"body":"default","mass":10,"fixedRotation":true},"sprite10":{"id":"sprite10","type":"sprite","visible":"true","x":144,"y":141,"width":34,"height":24,"image":"bird_death","frame":0,"scaleX":1,"scaleY":1,"rotation":0,"physics":false,"dynamic":true,"body":"default","mass":10,"fixedRotation":true}}
var gameover_config={"backgroundColor":"#000000","world":{"x":0,"y":0,"width":"320","height":"480","collideWorldBounds":false},"camera":{"x":0,"y":0,"width":"320","height":"480"},"physics":{"enable":false,"type":"ARCADE","gravityX":0,"gravityY":0},"input":{"onDown":"","onHold":"","onTap":"","onUp":""}}
var gameover=function(game){this.game=game;this.sceneName="gameover";this.sceneRes=gameover_res;this.sceneNode=gameover_scn;this.worldConfig=gameover_config;this.isLoadComplete=false;this.isCreateFinished=false;this.objects={};this.physicType="ARCADE";};gameover.prototype={preload:function(){this.customLoad();},create:function(){var worldConfig=this.worldConfig;if(parseBoolean(worldConfig.physics.enable)){this.physicType=worldConfig.physics.type;if(this.worldConfig.physics.type="ARCADE"){this.game.physics.startSystem(Phaser.Physics.ARCADE);this.game.physics.arcade.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.arcade.gravity.y=parseInt(worldConfig.physics.gravityY);}else if(worldConfig.physics.type="P2JS"){this.game.physics.startSystem(Phaser.Physics.P2JS);this.game.physics.p2.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.p2.gravity.y=parseInt(worldConfig.physics.gravityY);}}
for(ev in worldConfig.input){if(worldConfig.input[ev]!="")
this.game.input[ev].add(this[worldConfig.input[ev]],this);}
this.stage.backgroundColor=worldConfig.backgroundColor;this.world.setBounds(parseInt(worldConfig.world.x),parseInt(worldConfig.world.y),parseInt(worldConfig.world.width),parseInt(worldConfig.world.height));this.camera.bounds=new Phaser.Rectangle(parseInt(worldConfig.camera.x),parseInt(worldConfig.camera.y),parseInt(worldConfig.camera.width),parseInt(worldConfig.camera.height));this.load.onLoadComplete.addOnce(this.loadComplete,this);for(i in this.sceneRes){LoadRes(this,this.sceneRes[i]);}
this.load.start();},loadComplete:function(){for(i in this.sceneNode){this.objects[this.sceneNode[i].id]=createObject(this,this.sceneNode[i]);if(typeof this.sceneNode[i].group!='undefined'){this.objects[this.sceneNode[i].group].add(this.objects[this.sceneNode[i].id]);}}
this.isLoadComplete=true;this.customCreate();this.isCreateFinished=true;},update:function(){if(this.isCreateFinished){this.customUpdate();}
else{this.customPreUpdate();}},customLoad:function(){},customCreate:function(){},customPreUpdate:function(){},customUpdate:function(){},shutdown:function(){for(obj in this.objects){game.world.remove(this.objects[obj]);}}};gameover.prototype.customUpdate=function(){}
gameover.prototype.customCreate=function(){console.log('gameover');}
gameover.prototype.sprite7_onInputDown=function(){game.state.start('gameplay');}