var main_res={}
var main_scn={"image0":{"id":"image0","type":"image","visible":"true","x":0,"y":0,"width":"600","height":"600","image":"bg","scaleX":1.6304347826086956,"scaleY":1.0416666666666667,"anchorX":0,"anchorY":0,"rotation":0},"grounds":{"id":"grounds","type":"group","visible":"true","x":0,"y":0,"physics":false,"children":{"sprite1":{"id":"sprite1","type":"sprite","visible":"true","x":34,"y":456,"width":109,"height":25,"image":"ground","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true},"sprite2":{"id":"sprite2","type":"sprite","visible":"true","x":182,"y":384,"width":109,"height":25,"image":"ground","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true},"sprite3":{"id":"sprite3","type":"sprite","visible":"true","x":324,"y":331,"width":109,"height":25,"image":"ground","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true},"sprite4":{"id":"sprite4","type":"sprite","visible":"true","x":468,"y":277,"width":109,"height":25,"image":"ground","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true}}},"sprite7":{"id":"sprite7","type":"sprite","visible":"true","x":64,"y":399,"width":27,"height":40,"image":"dude","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"true","body":"default","mass":10,"fixedRotation":true}}
var main_config={"backgroundColor":"#000000","world":{"x":0,"y":0,"width":"600","height":"600","collideWorldBounds":false},"camera":{"x":0,"y":0,"width":"600","height":"600"},"physics":{"enable":"true","type":"ARCADE","gravityX":0,"gravityY":"980"},"input":{"onDown":"","onHold":"","onTap":"","onUp":""}}
var main=function(game){this.game=game;this.sceneName="main";this.sceneRes=main_res;this.sceneNode=main_scn;this.worldConfig=main_config;this.isLoadComplete=false;this.isCreateFinished=false;this.objects={};this.physicType="ARCADE";};main.prototype={preload:function(){this.customLoad();},create:function(){var worldConfig=this.worldConfig;this.stage.backgroundColor=worldConfig.backgroundColor;this.world.setBounds(parseInt(worldConfig.world.x),parseInt(worldConfig.world.y),parseInt(worldConfig.world.width),parseInt(worldConfig.world.height));if(parseBoolean(worldConfig.physics.enable)){this.physicType=worldConfig.physics.type;if(this.worldConfig.physics.type=="ARCADE"){this.game.physics.startSystem(Phaser.Physics.ARCADE);this.game.physics.arcade.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.arcade.gravity.y=parseInt(worldConfig.physics.gravityY);}else if(worldConfig.physics.type=="P2JS"){this.game.physics.startSystem(Phaser.Physics.P2JS);this.game.physics.p2.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.p2.gravity.y=parseInt(worldConfig.physics.gravityY);}}
for(ev in worldConfig.input){if(worldConfig.input[ev]!="")
this.game.input[ev].add(this[worldConfig.input[ev]],this);}
this.load.onLoadComplete.addOnce(this.loadComplete,this);for(i in this.sceneRes){LoadRes(this,this.sceneRes[i]);}
this.load.start();},loadComplete:function(){for(i in this.sceneNode){this.objects[this.sceneNode[i].id]=createObject(this,this.sceneNode[i]);if(typeof this.sceneNode[i].group!='undefined'){this.objects[this.sceneNode[i].group].add(this.objects[this.sceneNode[i].id]);}}
this.isLoadComplete=true;this.customCreate();this.isCreateFinished=true;},update:function(){if(this.isCreateFinished){this.customUpdate();}
else{this.customPreUpdate();}},customLoad:function(){},customCreate:function(){},customPreUpdate:function(){},customUpdate:function(){},shutdown:function(){for(obj in this.objects){game.world.remove(this.objects[obj]);}
this.objects={};for(res in this.sceneRes){removeRes(this,this.sceneRes[res]);}
this.sceneRes={};}};main.prototype.customLoad=function(){}
main.prototype.customCreate=function(){}
main.prototype.customUpdate=function(){game.physics.arcade.collide(this.objects.sprite7,this.objects.grounds);if(game.input.keyboard.isDown(Phaser.Keyboard.LEFT))
this.objects.sprite7.body.velocity.x=-100;else if(game.input.keyboard.isDown(Phaser.Keyboard.RIGHT))
this.objects.sprite7.body.velocity.x=100;else
this.objects.sprite7.body.velocity.x=0;if(game.input.keyboard.isDown(Phaser.Keyboard.UP))
if(this.objects.sprite7.body.touching.down)
this.objects.sprite7.body.velocity.y=-500;}