var main_res={}
var main_scn={"sprite0":{"id":"sprite0","type":"sprite","visible":"true","x":317,"y":60,"width":64,"height":64,"image":"mushroom2","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":false,"dynamic":true,"body":"default","mass":10,"fixedRotation":true},"animate1":{"id":"animate1","type":"animate","visible":"true","x":122,"y":124,"width":90,"height":90,"image":"character","animations":{"stand":{"frameRate":"6","loop":true,"sequence":[0,1,2,3]}},"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":false,"dynamic":true,"body":"default","mass":10,"fixedRotation":true},"text3":{"id":"text3","type":"text","visible":"true","x":362,"y":179,"text":"text","fontFamily":"Arial","fontSize":"32","fontColor":"#fff","textAlign":"left"},"audio0":{"id":"audio0","type":"audio","audio":"fx_mixdown","tracks":{"trac":{"start":1,"duration":1,"loop":false}}},"sprite1":{"id":"sprite1","type":"sprite","visible":"true","x":254,"y":247,"width":104,"height":58,"image":"play","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":false,"dynamic":true,"body":"default","mass":10,"fixedRotation":true,"events":{"onInputDown":"sprite1_onInputDown"}}}
var main_config={"backgroundColor":"#000000","world":{"x":0,"y":0,"width":"800","height":"600","collideWorldBounds":false},"camera":{"x":0,"y":0,"width":"800","height":"600"},"physics":{"enable":false,"type":"ARCADE","gravityX":0,"gravityY":0},"input":{"onDown":"","onHold":"","onTap":"","onUp":""}}
var main=function(game){this.game=game;this.sceneName="main";this.sceneRes=main_res;this.sceneNode=main_scn;this.worldConfig=main_config;this.isLoadComplete=false;this.isCreateFinished=false;this.objects={};this.physicType="ARCADE";};main.prototype={preload:function(){this.customLoad();},create:function(){var worldConfig=this.worldConfig;if(parseBoolean(worldConfig.physics.enable)){this.physicType=worldConfig.physics.type;if(this.worldConfig.physics.type=="ARCADE"){this.game.physics.startSystem(Phaser.Physics.ARCADE);this.game.physics.arcade.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.arcade.gravity.y=parseInt(worldConfig.physics.gravityY);}else if(worldConfig.physics.type=="P2JS"){this.game.physics.startSystem(Phaser.Physics.P2JS);this.game.physics.p2.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.p2.gravity.y=parseInt(worldConfig.physics.gravityY);}}
for(ev in worldConfig.input){if(worldConfig.input[ev]!="")
this.game.input[ev].add(this[worldConfig.input[ev]],this);}
this.stage.backgroundColor=worldConfig.backgroundColor;this.world.setBounds(parseInt(worldConfig.world.x),parseInt(worldConfig.world.y),parseInt(worldConfig.world.width),parseInt(worldConfig.world.height));this.camera.bounds=new Phaser.Rectangle(parseInt(worldConfig.camera.x),parseInt(worldConfig.camera.y),parseInt(worldConfig.camera.width),parseInt(worldConfig.camera.height));this.load.onLoadComplete.addOnce(this.loadComplete,this);for(i in this.sceneRes){LoadRes(this,this.sceneRes[i]);}
this.load.start();},loadComplete:function(){for(i in this.sceneNode){this.objects[this.sceneNode[i].id]=createObject(this,this.sceneNode[i]);if(typeof this.sceneNode[i].group!='undefined'){this.objects[this.sceneNode[i].group].add(this.objects[this.sceneNode[i].id]);}}
this.isLoadComplete=true;this.customCreate();this.isCreateFinished=true;},update:function(){if(this.isCreateFinished){this.customUpdate();}
else{this.customPreUpdate();}},customLoad:function(){},customCreate:function(){},customPreUpdate:function(){},customUpdate:function(){},shutdown:function(){for(obj in this.objects){game.world.remove(this.objects[obj]);}
this.objects={};for(res in this.sceneRes){removeRes(this,this.sceneRes[res]);}
this.sceneRes={};}};main.prototype.customLoad=function(){}
main.prototype.customCreate=function(){this.objects.animate1.animations.play('stand');}
main.prototype.customUpdate=function(){}
main.prototype.sprite1_onInputDown=function(){this.objects.audio0.play('trac');}