var main_res={}
var main_scn={"image5":{"id":"image5","type":"image","visible":"true","x":0,"y":0,"width":"800","height":"600","image":"bg","scaleX":2.1739130434782608,"scaleY":1.0416666666666667,"anchorX":0,"anchorY":0,"rotation":0},"group1":{"id":"group1","type":"physicsgroup","visible":"true","x":0,"y":0},"sprite0":{"id":"sprite0","type":"sprite","visible":"true","x":303,"y":524,"width":124,"height":37,"image":"board","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true},"sprite2":{"id":"sprite2","type":"sprite","visible":"true","x":343,"y":482,"width":40,"height":40,"image":"ball","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":true,"body":"default","mass":10,"fixedRotation":true},"walls":{"id":"walls","type":"group","visible":"true","x":0,"y":0,"physics":false,"children":{"sprite1":{"id":"sprite1","type":"sprite","visible":"true","x":"0","y":"-16","width":"800","height":"16","image":"board","frame":0,"scaleX":6.451612903225806,"scaleY":0.43243243243243246,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true},"sprite3":{"id":"sprite3","type":"sprite","visible":"true","x":"-16","y":"0","width":"16","height":"600","image":"board","frame":0,"scaleX":0.12903225806451613,"scaleY":16.216216216216218,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true},"sprite4":{"id":"sprite4","type":"sprite","visible":"true","x":"800","y":"0","width":"16","height":"600","image":"board","frame":0,"scaleX":0.12903225806451613,"scaleY":16.216216216216218,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true}}}}
var main_config={"backgroundColor":"#000000","world":{"x":0,"y":0,"width":"800","height":"600","collideWorldBounds":false},"camera":{"x":0,"y":0,"width":"800","height":"600"},"physics":{"enable":"true","type":"ARCADE","gravityX":0,"gravityY":0},"input":{"onDown":"","onHold":"","onTap":"","onUp":""}}
var main=function(game){this.game=game;this.sceneName="main";this.sceneRes=main_res;this.sceneNode=main_scn;this.worldConfig=main_config;this.isLoadComplete=false;this.isCreateFinished=false;this.objects={};this.physicType="ARCADE";};main.prototype={preload:function(){this.customLoad();},create:function(){var worldConfig=this.worldConfig;if(parseBoolean(worldConfig.physics.enable)){this.physicType=worldConfig.physics.type;if(this.worldConfig.physics.type=="ARCADE"){this.game.physics.startSystem(Phaser.Physics.ARCADE);this.game.physics.arcade.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.arcade.gravity.y=parseInt(worldConfig.physics.gravityY);}else if(worldConfig.physics.type=="P2JS"){this.game.physics.startSystem(Phaser.Physics.P2JS);this.game.physics.p2.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.p2.gravity.y=parseInt(worldConfig.physics.gravityY);}}
for(ev in worldConfig.input){if(worldConfig.input[ev]!="")
this.game.input[ev].add(this[worldConfig.input[ev]],this);}
this.stage.backgroundColor=worldConfig.backgroundColor;this.world.setBounds(parseInt(worldConfig.world.x),parseInt(worldConfig.world.y),parseInt(worldConfig.world.width),parseInt(worldConfig.world.height));this.load.onLoadComplete.addOnce(this.loadComplete,this);for(i in this.sceneRes){LoadRes(this,this.sceneRes[i]);}
this.load.start();},loadComplete:function(){for(i in this.sceneNode){this.objects[this.sceneNode[i].id]=createObject(this,this.sceneNode[i]);if(typeof this.sceneNode[i].group!='undefined'){this.objects[this.sceneNode[i].group].add(this.objects[this.sceneNode[i].id]);}}
this.isLoadComplete=true;this.customCreate();this.isCreateFinished=true;},update:function(){if(this.isCreateFinished){this.customUpdate();}
else{this.customPreUpdate();}},customLoad:function(){},customCreate:function(){},customPreUpdate:function(){},customUpdate:function(){},shutdown:function(){for(obj in this.objects){game.world.remove(this.objects[obj]);}
this.objects={};for(res in this.sceneRes){removeRes(this,this.sceneRes[res]);}
this.sceneRes={};}};var startv={x:500,y:-500};var oldv={x:0,y:0};main.prototype.customLoad=function(){};main.prototype.customCreate=function(){for(i=1;i<=6;i++){for(j=1;j<=4;j++){var block=this.objects.group1.create(i*96,j*48,'block'+i);block.body.immovable=true;}}
this.objects.sprite0.body.collideWorldBounds=true;};main.prototype.customUpdate=function(){game.physics.arcade.collide(this.objects.sprite2,this.objects.group1,this.reflect);game.physics.arcade.collide(this.objects.sprite2,this.objects.sprite0,this.reflect);game.physics.arcade.collide(this.objects.sprite2,this.objects.walls,this.reflect);if(this.objects.sprite2.y>=600){this.objects.sprite2.position.set(this.objects.sprite0.x+this.objects.sprite0.width/2,482);oldv.x=0;oldv.y=0;}
this.objects.sprite2.body.velocity.y=oldv.y;this.objects.sprite2.body.velocity.x=oldv.x;if(game.input.keyboard.isDown(Phaser.Keyboard.LEFT)){this.objects.sprite0.body.velocity.x=-1000;}else if(game.input.keyboard.isDown(Phaser.Keyboard.RIGHT)){this.objects.sprite0.body.velocity.x=1000;}else{this.objects.sprite0.body.velocity.x=0;}
if(oldv.x===0&&oldv.y===0){this.objects.sprite2.body.velocity.x=this.objects.sprite0.body.velocity.x;if(game.input.keyboard.isDown(Phaser.Keyboard.UP)){oldv.x=startv.x;oldv.y=startv.y;}}
this.objects.sprite0.body.velocity.y=0;}
main.prototype.reflect=function(ball,block){if(block.body.touching.up||block.body.touching.down){oldv.y=-oldv.y;}else
oldv.x=-oldv.x;if(block.key!=='board')block.kill();}