var preload_res={"bg":{"id":"bg","type":"image","path":"data/bg.png","height":576,"width":368},"ready":{"id":"ready","type":"image","path":"data/ready.png","height":50,"width":184},"play":{"id":"play","type":"image","path":"data/play.png","height":58,"width":104},"scores":{"id":"scores","type":"image","path":"data/scores.png","height":58,"width":104},"title":{"id":"title","type":"image","path":"data/title.png","height":48,"width":178},"bird_fly":{"id":"bird_fly","type":"spritesheet","path":"data/bird_fly.png","Xframe":"3","Yframe":"1","width":102,"height":24},"ground":{"id":"ground","type":"image","path":"data/ground.png","height":123,"width":368},"pipe_down":{"id":"pipe_down","type":"image","path":"data/pipe_down.png","height":320,"width":52},"pipe_up":{"id":"pipe_up","type":"image","path":"data/pipe_up.png","height":320,"width":52},"restart":{"id":"restart","type":"image","path":"data/restart.png","height":96,"width":96},"game":{"id":"game","type":"image","path":"data/game.png","height":42,"width":102},"over":{"id":"over","type":"image","path":"data/over.png","height":42,"width":88},"bird_death":{"id":"bird_death","type":"image","path":"data/bird_death.png","height":24,"width":34}}
var preload_scn={}
var preload_config={"backgroundColor":"#000000","world":{"x":0,"y":0,"width":"320","height":"480","collideWorldBounds":false},"camera":{"x":0,"y":0,"width":"320","height":"480"},"physics":{"enable":false,"type":"ARCADE","gravityX":0,"gravityY":0},"input":{"onDown":"","onHold":"","onTap":"","onUp":""}}
var preload=function(game){this.game=game;this.sceneName="preload";this.sceneRes=preload_res;this.sceneNode=preload_scn;this.worldConfig=preload_config;this.isLoadComplete=false;this.isCreateFinished=false;this.objects={};this.physicType="ARCADE";};preload.prototype={preload:function(){this.customLoad();},create:function(){var worldConfig=this.worldConfig;if(parseBoolean(worldConfig.physics.enable)){this.physicType=worldConfig.physics.type;if(this.worldConfig.physics.type="ARCADE"){this.game.physics.startSystem(Phaser.Physics.ARCADE);this.game.physics.arcade.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.arcade.gravity.y=parseInt(worldConfig.physics.gravityY);}else if(worldConfig.physics.type="P2JS"){this.game.physics.startSystem(Phaser.Physics.P2JS);this.game.physics.p2.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.p2.gravity.y=parseInt(worldConfig.physics.gravityY);}}
for(ev in worldConfig.input){if(worldConfig.input[ev]!="")
this.game.input[ev].add(this[worldConfig.input[ev]],this);}
this.stage.backgroundColor=worldConfig.backgroundColor;this.world.setBounds(parseInt(worldConfig.world.x),parseInt(worldConfig.world.y),parseInt(worldConfig.world.width),parseInt(worldConfig.world.height));this.camera.bounds=new Phaser.Rectangle(parseInt(worldConfig.camera.x),parseInt(worldConfig.camera.y),parseInt(worldConfig.camera.width),parseInt(worldConfig.camera.height));this.load.onLoadComplete.addOnce(this.loadComplete,this);for(i in this.sceneRes){LoadRes(this,this.sceneRes[i]);}
this.load.start();},loadComplete:function(){for(i in this.sceneNode){this.objects[this.sceneNode[i].id]=createObject(this,this.sceneNode[i]);if(typeof this.sceneNode[i].group!='undefined'){this.objects[this.sceneNode[i].group].add(this.objects[this.sceneNode[i].id]);}}
this.isLoadComplete=true;this.customCreate();this.isCreateFinished=true;},update:function(){if(this.isCreateFinished){this.customUpdate();}
else{this.customPreUpdate();}},customLoad:function(){},customCreate:function(){},customPreUpdate:function(){},customUpdate:function(){},shutdown:function(){for(obj in this.objects){game.world.remove(this.objects[obj]);}}};preload.prototype.customUpdate=function(){game.state.start('mainmenu');}