var main_res={}
var main_scn={"tilemap0":{"id":"tilemap0","type":"tilemap","visible":"true","tileW":30,"tileH":15,"tilesetW":32,"tilesetH":32,"tilemap":"level1","tileset":["mytile"]},"star3":{"id":"star3","type":"sprite","visible":"true","x":708,"y":132,"width":22,"height":21,"image":"star","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true},"door":{"id":"door","type":"sprite","visible":"true","x":67,"y":96,"width":25,"height":32,"image":"door","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true},"tunnel3":{"id":"tunnel3","type":"sprite","visible":"true","x":802,"y":359,"width":28,"height":23,"image":"tunnel","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true},"tunnel2":{"id":"tunnel2","type":"sprite","visible":"true","x":576,"y":68,"width":28,"height":23,"image":"tunnel","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true},"star1":{"id":"star1","type":"sprite","visible":"true","x":581,"y":101,"width":22,"height":21,"image":"star","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true},"star2":{"id":"star2","type":"sprite","visible":"true","x":164,"y":357,"width":22,"height":21,"image":"star","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true},"layer1":{"id":"layer1","type":"group","visible":"true","x":0,"y":0,"physics":false},"layer2":{"id":"layer2","type":"group","visible":"true","x":0,"y":0,"physics":false},"tunnel4":{"id":"tunnel4","type":"sprite","visible":"true","x":33,"y":292,"width":28,"height":23,"image":"tunnel","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true},"player":{"id":"player","type":"sprite","visible":"true","x":384,"y":401,"width":27,"height":40,"image":"dude","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"true","body":"default","mass":10,"fixedRotation":true}}
var main_config={"backgroundColor":"#000000","world":{"x":0,"y":0,"width":"800","height":"600","collideWorldBounds":false},"camera":{"x":0,"y":0,"width":"800","height":"600"},"physics":{"enable":"true","type":"ARCADE","gravityX":0,"gravityY":"980"},"input":{"onDown":"","onHold":"","onTap":"","onUp":""}}
var main=function(game){this.game=game;this.sceneName="main";this.sceneRes=main_res;this.sceneNode=main_scn;this.worldConfig=main_config;this.isLoadComplete=false;this.isCreateFinished=false;this.objects={};this.physicType="ARCADE";};main.prototype={preload:function(){this.customLoad();},create:function(){var worldConfig=this.worldConfig;if(parseBoolean(worldConfig.physics.enable)){this.physicType=worldConfig.physics.type;if(this.worldConfig.physics.type=="ARCADE"){this.game.physics.startSystem(Phaser.Physics.ARCADE);this.game.physics.arcade.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.arcade.gravity.y=parseInt(worldConfig.physics.gravityY);}else if(worldConfig.physics.type=="P2JS"){this.game.physics.startSystem(Phaser.Physics.P2JS);this.game.physics.p2.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.p2.gravity.y=parseInt(worldConfig.physics.gravityY);}}
for(ev in worldConfig.input){if(worldConfig.input[ev]!="")
this.game.input[ev].add(this[worldConfig.input[ev]],this);}
this.stage.backgroundColor=worldConfig.backgroundColor;this.world.setBounds(parseInt(worldConfig.world.x),parseInt(worldConfig.world.y),parseInt(worldConfig.world.width),parseInt(worldConfig.world.height));this.camera.bounds=new Phaser.Rectangle(parseInt(worldConfig.camera.x),parseInt(worldConfig.camera.y),parseInt(worldConfig.camera.width),parseInt(worldConfig.camera.height));this.load.onLoadComplete.addOnce(this.loadComplete,this);for(i in this.sceneRes){LoadRes(this,this.sceneRes[i]);}
this.load.start();},loadComplete:function(){for(i in this.sceneNode){this.objects[this.sceneNode[i].id]=createObject(this,this.sceneNode[i]);if(typeof this.sceneNode[i].group!='undefined'){this.objects[this.sceneNode[i].group].add(this.objects[this.sceneNode[i].id]);}}
this.isLoadComplete=true;this.customCreate();this.isCreateFinished=true;},update:function(){if(this.isCreateFinished){this.customUpdate();}
else{this.customPreUpdate();}},customLoad:function(){},customCreate:function(){},customPreUpdate:function(){},customUpdate:function(){},shutdown:function(){for(obj in this.objects){game.world.remove(this.objects[obj]);}
this.objects={};for(res in this.sceneRes){removeRes(this,this.sceneRes[res]);}
this.sceneRes={};}};var currentLayer;var delay=0;var layergroup;var canChange;main.prototype.customLoad=function(){}
main.prototype.customCreate=function(){currentLayer=this.objects.tilemap0.createLayer('layer1');currentLayer.resizeWorld();this.objects.tilemap0.setLayer(currentLayer);this.objects.tilemap0.setCollisionBetween(1,23);game.camera.follow(this.objects.player);this.objects.layer2.add(this.objects.star3);this.objects.layer2.add(this.objects.star2);this.objects.layer2.add(this.objects.door);this.objects.layer2.add(this.objects.tunnel2);this.objects.layer1.add(this.objects.tunnel3);this.objects.layer1.add(this.objects.tunnel4);this.objects.layer1.add(this.objects.star1);layergroup=this.objects.layer1;this.objects.layer2.visible=false;}
main.prototype.customUpdate=function(){canChange=false;game.physics.arcade.collide(this.objects.player,currentLayer);game.physics.arcade.overlap(this.objects.player,layergroup,this.collision,null,this);this.objects.player.body.velocity.x=0;if(game.input.keyboard.isDown(Phaser.Keyboard.LEFT))
this.objects.player.body.velocity.x=-100;else if(game.input.keyboard.isDown(Phaser.Keyboard.RIGHT))
this.objects.player.body.velocity.x=100;if(this.objects.player.body.onFloor()&&game.input.keyboard.isDown(Phaser.Keyboard.UP))
this.objects.player.body.velocity.y=-400;if(canChange&&game.input.keyboard.isDown(Phaser.Keyboard.E)&&delay>50){var layername=currentLayer.layer.name;currentLayer.destroy();layergroup.visible=false;if(layername=='layer1'){currentLayer=this.objects.tilemap0.createLayer('layer2');layergroup=this.objects.layer2;}else{currentLayer=this.objects.tilemap0.createLayer('layer1');layergroup=this.objects.layer1;}
layergroup.visible=true;this.objects.tilemap0.setLayer(currentLayer);currentLayer.resizeWorld();this.objects.tilemap0.setCollisionBetween(1,23);delay=0;}
delay++;}
main.prototype.collision=function(player,g){if(g.key=='tunnel')
canChange=true;else if(g.key=='star')
g.kill();else if(g.key=='door')
game.state.start('mainmenu');}