var main_res={}
var main_scn={"sprite0":{"id":"sprite0","type":"sprite","visible":"true","x":165,"y":211,"width":40,"height":207,"image":"right","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":false,"dynamic":true,"body":"default","mass":10,"fixedRotation":true},"bird":{"id":"bird","type":"sprite","visible":"true","x":158,"y":251.5,"width":104,"height":101,"image":"bird","frame":0,"scaleX":1,"scaleY":1,"anchorX":"0.5","anchorY":"0.5","rotation":0,"physics":false,"dynamic":true,"body":"default","mass":10,"fixedRotation":true},"sprite1":{"id":"sprite1","type":"sprite","visible":"true","x":134,"y":206,"width":44,"height":127,"image":"left","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":false,"dynamic":true,"body":"default","mass":10,"fixedRotation":true},"sprite3":{"id":"sprite3","type":"sprite","visible":"true","x":511,"y":444,"width":1024,"height":64,"image":"ground","frame":0,"scaleX":"1.0","scaleY":1,"anchorX":"0.5","anchorY":"0.5","rotation":0,"physics":"true","dynamic":"false","body":"default","mass":10,"fixedRotation":true}}
var main_config={"backgroundColor":"#000000","world":{"x":0,"y":0,"width":"1024","height":"480","collideWorldBounds":false},"camera":{"x":0,"y":0,"width":"640","height":"480"},"physics":{"enable":"true","type":"P2JS","gravityX":0,"gravityY":0},"input":{"onDown":"","onHold":"","onTap":"","onUp":""}}
var main=function(game){this.game=game;this.sceneName="main";this.sceneRes=main_res;this.sceneNode=main_scn;this.worldConfig=main_config;this.isLoadComplete=false;this.isCreateFinished=false;this.objects={};this.physicType="ARCADE";};main.prototype={preload:function(){this.customLoad();},create:function(){var worldConfig=this.worldConfig;if(parseBoolean(worldConfig.physics.enable)){this.physicType=worldConfig.physics.type;if(this.worldConfig.physics.type=="ARCADE"){this.game.physics.startSystem(Phaser.Physics.ARCADE);this.game.physics.arcade.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.arcade.gravity.y=parseInt(worldConfig.physics.gravityY);}else if(worldConfig.physics.type=="P2JS"){this.game.physics.startSystem(Phaser.Physics.P2JS);this.game.physics.p2.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.p2.gravity.y=parseInt(worldConfig.physics.gravityY);}}
for(ev in worldConfig.input){if(worldConfig.input[ev]!="")
this.game.input[ev].add(this[worldConfig.input[ev]],this);}
this.stage.backgroundColor=worldConfig.backgroundColor;this.world.setBounds(parseInt(worldConfig.world.x),parseInt(worldConfig.world.y),parseInt(worldConfig.world.width),parseInt(worldConfig.world.height));this.camera.bounds=new Phaser.Rectangle(parseInt(worldConfig.camera.x),parseInt(worldConfig.camera.y),parseInt(worldConfig.camera.width),parseInt(worldConfig.camera.height));this.load.onLoadComplete.addOnce(this.loadComplete,this);for(i in this.sceneRes){LoadRes(this,this.sceneRes[i]);}
this.load.start();},loadComplete:function(){for(i in this.sceneNode){this.objects[this.sceneNode[i].id]=createObject(this,this.sceneNode[i]);if(typeof this.sceneNode[i].group!='undefined'){this.objects[this.sceneNode[i].group].add(this.objects[this.sceneNode[i].id]);}}
this.isLoadComplete=true;this.customCreate();this.isCreateFinished=true;},update:function(){if(this.isCreateFinished){this.customUpdate();}
else{this.customPreUpdate();}},customLoad:function(){},customCreate:function(){},customPreUpdate:function(){},customUpdate:function(){},shutdown:function(){for(obj in this.objects){game.world.remove(this.objects[obj]);}
this.objects={};for(res in this.sceneRes){removeRes(this,this.sceneRes[res]);}
this.sceneRes={};}};main.prototype.customLoad=function(){};main.prototype.customCreate=function(){game.world.setBounds(0,0,1024,480);game.physics.p2.gravity.y=980;game.camera.follow(this.objects.bird);this.objects.bird.inputEnabled=true;this.objects.bird.input.enableDrag();this.objects.bird.events.onDragStop.add(this.shot,this);};main.prototype.customUpdate=function(){if(this.objects.bird.x>=1124||this.objects.bird.x<=-100){console.log('out of bounds');this.objects.bird.position.set(158,250);this.objects.bird.body=null;}};main.prototype.shot=function(){game.physics.p2.enable(this.objects.bird);this.objects.bird.body.velocity.x=(158-this.objects.bird.x+50)*5;this.objects.bird.body.velocity.y=(250-this.objects.bird.y)*10;};