var main_res={}
var main_scn={"sprite0":{"id":"sprite0","type":"sprite","visible":"true","x":186,"y":496,"width":75,"height":64,"image":"ship","frame":0,"scaleX":1,"scaleY":1,"anchorX":0,"anchorY":0,"rotation":0,"physics":"true","dynamic":"true","body":"default","mass":10,"fixedRotation":true},"enemies":{"id":"enemies","type":"physicsgroup","visible":"true","x":0,"y":0},"bullets":{"id":"bullets","type":"physicsgroup","visible":"true","x":0,"y":0}}
var main_config={"backgroundColor":"#000000","world":{"x":0,"y":0,"width":"480","height":"600","collideWorldBounds":false},"camera":{"x":0,"y":0,"width":"800","height":"600"},"physics":{"enable":"true","type":"ARCADE","gravityX":0,"gravityY":0},"input":{"onDown":"","onHold":"","onTap":"","onUp":""}}
var main=function(game){this.game=game;this.sceneName="main";this.sceneRes=main_res;this.sceneNode=main_scn;this.worldConfig=main_config;this.isLoadComplete=false;this.isCreateFinished=false;this.objects={};this.physicType="ARCADE";};main.prototype={preload:function(){this.customLoad();},create:function(){var worldConfig=this.worldConfig;this.stage.backgroundColor=worldConfig.backgroundColor;this.world.setBounds(parseInt(worldConfig.world.x),parseInt(worldConfig.world.y),parseInt(worldConfig.world.width),parseInt(worldConfig.world.height));if(parseBoolean(worldConfig.physics.enable)){this.physicType=worldConfig.physics.type;if(this.worldConfig.physics.type=="ARCADE"){this.game.physics.startSystem(Phaser.Physics.ARCADE);this.game.physics.arcade.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.arcade.gravity.y=parseInt(worldConfig.physics.gravityY);}else if(worldConfig.physics.type=="P2JS"){this.game.physics.startSystem(Phaser.Physics.P2JS);this.game.physics.p2.gravity.x=parseInt(worldConfig.physics.gravityX);this.game.physics.p2.gravity.y=parseInt(worldConfig.physics.gravityY);}}
for(ev in worldConfig.input){if(worldConfig.input[ev]!="")
this.game.input[ev].add(this[worldConfig.input[ev]],this);}
this.load.onLoadComplete.addOnce(this.loadComplete,this);for(i in this.sceneRes){LoadRes(this,this.sceneRes[i]);}
this.load.start();},loadComplete:function(){for(i in this.sceneNode){this.objects[this.sceneNode[i].id]=createObject(this,this.sceneNode[i]);if(typeof this.sceneNode[i].group!='undefined'){this.objects[this.sceneNode[i].group].add(this.objects[this.sceneNode[i].id]);}}
this.isLoadComplete=true;this.customCreate();this.isCreateFinished=true;},update:function(){if(this.isCreateFinished){this.customUpdate();}
else{this.customPreUpdate();}},customLoad:function(){},customCreate:function(){},customPreUpdate:function(){},customUpdate:function(){},shutdown:function(){for(obj in this.objects){game.world.remove(this.objects[obj]);}
this.objects={};for(res in this.sceneRes){removeRes(this,this.sceneRes[res]);}
this.sceneRes={};}};var delay=0;main.prototype.customLoad=function(){}
main.prototype.customCreate=function(){for(i=0;i<6;i++){var enemy=this.objects.enemies.create(Math.random()*400,-96*i,'enemy');enemy.body.velocity.y=200;enemy.checkWorldBounds=true;enemy.events.onOutOfBounds.add(this.resetenemy,this);}
this.objects.sprite0.body.collideWorldBounds=true;}
main.prototype.customUpdate=function(){game.physics.arcade.collide(this.objects.enemies,this.objects.bullets,this.boom);game.physics.arcade.collide(this.objects.sprite0,this.objects.enemies,this.crash);if(game.input.keyboard.isDown(Phaser.Keyboard.LEFT))
this.objects.sprite0.body.velocity.x=-400;else if(game.input.keyboard.isDown(Phaser.Keyboard.RIGHT))
this.objects.sprite0.body.velocity.x=400;else if(game.input.keyboard.isDown(Phaser.Keyboard.UP))
this.objects.sprite0.body.velocity.y=-400;else if(game.input.keyboard.isDown(Phaser.Keyboard.DOWN))
this.objects.sprite0.body.velocity.y=400;else{this.objects.sprite0.body.velocity.x=0;this.objects.sprite0.body.velocity.y=0;}
if(delay++%15===0&&game.input.keyboard.isDown(Phaser.Keyboard.Z)){var bullet=this.objects.bullets.create(this.objects.sprite0.x+10,500,'bullet');bullet.body.velocity.y=-200;bullet.outOfBoundsKill=true;bullet.checkWorldBounds=true;}};main.prototype.resetenemy=function(sprite){if(sprite.y>600){sprite.position.set(Math.random()*400,-64-Math.random()*100);sprite.body.velocity.y=200;}}
main.prototype.boom=function(sprite,bullet){bullet.kill();sprite.position.set(Math.random()*400,-64-Math.random()*100);sprite.body.velocity.x=0;sprite.body.velocity.y=200;}
main.prototype.crash=function(ship,sprite){sprite.position.set(Math.random()*400,-64-Math.random()*100);sprite.body.velocity.x=0;sprite.body.velocity.y=200;}